<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logout">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<?php $this->getUserPanel(); ?>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="POST" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $key => $value) { ?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $value['name'] ?></strong> - <small><span class="text text-muted"><?= $value['data'] ?></span></small></p>
						<p><?= $value['tweet'] ?></p>
						<br />
						<?php if ($value['id_user'] == $_SESSION['id']) { ?>
							<form>
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/who_to_follow" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>