<?php $this->getNavBar(); ?>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<?php $this->getUserPanel(); ?>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="GET" action="who_to_follow">
								<div class="input-group mb-3">
									<input type="text" class="form-control" placeholder="Quem você está procurando?" name="searchFor">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php foreach($this->view->users as $key => $value) { ?> 
				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<?= $value['name']; ?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											<?php if ($value['follow'] == 0) { ?>
												<a href="/action?action=follow&id_user=<?= $value['id']; ?>" class="btn btn-success">Seguir</a>
											<?php } ?>
											<?php if ($value['follow'] == 1) {  ?>
												<a href="/action?action=unfollow&id_user=<?= $value['id']; ?>" class="btn btn-danger">Deixar de seguir</a>
											<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>

		</div>
	</div>
</div>